# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RickAndMorty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RickAndMorty
  pod 'RealmSwift'
  pod 'Realm'
  pod 'SwiftSoup'
  pod 'lottie-ios'
  
  target 'RickAndMortyTests' do
    inherit! :search_paths
  end
  
  target 'RickAndMortyUITests' do
  end
  
end
