# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all tests"
  lane :test do
    xcov(
  		workspace: "RickAndMorty.xcworkspace",
  		scheme: "RickAndMorty",
  		output_directory: "test_output",
  		exclude_targets: "Pods-RickAndMorty.framework,Pods-RickAndMorty-RickAndMortyUITests.framewor,Pods-RickAndMortyTests.framewor,Realm.framework,RealmSwift.framework,SwiftSoup.framework"
	)
  end
end
